/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesCandidatesIdRouteImport } from './routes/candidates.$candidatesId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidatesIdRoute = CandidatesCandidatesIdRouteImport.update({
  id: '/candidates/$candidatesId',
  path: '/candidates/$candidatesId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidatesId': typeof CandidatesCandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidatesId': typeof CandidatesCandidatesIdRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidatesId': typeof CandidatesCandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/candidates/$candidatesId' | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/candidates/$candidatesId' | '/candidates'
  id: '__root__' | '/' | '/about' | '/candidates/$candidatesId' | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandidatesCandidatesIdRoute: typeof CandidatesCandidatesIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidatesId': {
      id: '/candidates/$candidatesId'
      path: '/candidates/$candidatesId'
      fullPath: '/candidates/$candidatesId'
      preLoaderRoute: typeof CandidatesCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandidatesCandidatesIdRoute: CandidatesCandidatesIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
